// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFLtT0RXH1LdkrMKrvoBxFfz3DsiKwkyc',
    appId: '1:975594184646:web:c581d2525234e6e5c81cc7',
    messagingSenderId: '975594184646',
    projectId: 'nomad-ym-moodtracker',
    authDomain: 'nomad-ym-moodtracker.firebaseapp.com',
    storageBucket: 'nomad-ym-moodtracker.firebasestorage.app',
    measurementId: 'G-WNL6Z3Q1L0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7gZYRW41NUmWUCJnFYuONxiiLx08G3OU',
    appId: '1:975594184646:android:01d3ae48e3b4d460c81cc7',
    messagingSenderId: '975594184646',
    projectId: 'nomad-ym-moodtracker',
    storageBucket: 'nomad-ym-moodtracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP4IMoT4qORszLeW-CkS_QWzvpNagBhww',
    appId: '1:975594184646:ios:be1571a6e4b15d86c81cc7',
    messagingSenderId: '975594184646',
    projectId: 'nomad-ym-moodtracker',
    storageBucket: 'nomad-ym-moodtracker.firebasestorage.app',
    iosBundleId: 'com.example.moodTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAP4IMoT4qORszLeW-CkS_QWzvpNagBhww',
    appId: '1:975594184646:ios:be1571a6e4b15d86c81cc7',
    messagingSenderId: '975594184646',
    projectId: 'nomad-ym-moodtracker',
    storageBucket: 'nomad-ym-moodtracker.firebasestorage.app',
    iosBundleId: 'com.example.moodTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFLtT0RXH1LdkrMKrvoBxFfz3DsiKwkyc',
    appId: '1:975594184646:web:6b5c0d6bd38add50c81cc7',
    messagingSenderId: '975594184646',
    projectId: 'nomad-ym-moodtracker',
    authDomain: 'nomad-ym-moodtracker.firebaseapp.com',
    storageBucket: 'nomad-ym-moodtracker.firebasestorage.app',
    measurementId: 'G-M474M4SJB1',
  );

}